var = input('Digite algo:')
print('O valor digitado é do tipo:', type(var))
print('Só tem espaço?', var.isspace())
print('É um número?', var.isnumeric())
print('É alfabético?', var.isalpha())
print('É alfanumerico?', var.isalnum())
print('Está em Maiúscula?:', var.isupper())
print('Está em Minúscula?:', var.islower())
print('Está capitalizada?:', var.istitle())
